editAreaLoader.lang["pl"]={
new_document: "nowy dokument",
search_button: "znajdŸ i zamieñ",
search_command: "znajdŸ nastêpny",
search: "znajdŸ",
replace: "zamieñ",
replace_command: "zamieñ",
find_next: "nastêpny",
replace_all: "zamieñ wszystko",
reg_exp: "wyra¿enie regularne",
match_case: "uwzglêdnij wielkoœæ liter<br />",
not_found: "nie znaleziono.",
occurrence_replaced: "wyst¹pieñ zamieniono.",
search_field_empty: "Nie wprowadzono tekstu",
restart_search_at_begin: "Koniec dokumentu. Wyszukiwanie od pocz¹tku.",
move_popup: "przesuñ okienko wyszukiwania",
font_size: "Rozmiar",
go_to_line: "idŸ do linii",
go_to_line_prompt: "numer linii:",
undo: "cofnij",
redo: "przywróæ",
change_smooth_selection: "w³¹cz/wy³¹cz niektóre opcje wygl¹du (zaawansowane opcje wygl¹du obci¹¿aj¹ procesor)",
highlight: "w³¹cz/wy³¹cz podœwietlanie sk³adni",
reset_highlight: "odœwie¿ podœwietlanie sk³adni (jeœli rozsynchronizowa³o siê z tekstem)",
word_wrap: "toggle word wrapping mode",
help: "o programie",
save: "zapisz",
load: "otwórz",
line_abbr: "Ln",
char_abbr: "Zn",
position: "Pozycja",
total: "W sumie",
close_popup: "zamknij okienko",
shortcuts: "Skróty klawiaturowe",
add_tab: "dodaj wciêcie do zaznaczonego tekstu",
remove_tab: "usuñ wciêcie",
about_notice: "Uwaga: podœwietlanie sk³adni nie jest zalecane dla d³ugich tekstów",
toggle: "W³¹cz/wy³¹cz edytor",
accesskey: "Alt+",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Przetwarzanie...",
fullscreen: "fullscreen",
syntax_selection: "--Syntax--",
syntax_css: "CSS",
syntax_html: "HTML",
syntax_js: "Javascript",
syntax_php: "Php",
syntax_python: "Python",
syntax_vb: "Visual Basic",
syntax_xml: "Xml",
syntax_c: "C",
syntax_cpp: "CPP",
syntax_basic: "Basic",
syntax_pas: "Pascal",
syntax_brainfuck: "Brainfuck",
syntax_sql: "SQL",
syntax_ruby: "Ruby",
syntax_robotstxt: "Robots txt",
syntax_tsql: "T-SQL",
syntax_perl: "Perl",
syntax_coldfusion: "Coldfusion",
syntax_java: "Java",
close_tab: "Close file"
};
